### ISSUE TITLE
error 1.8.9

### ISSUE THREAD

**Issue by dinobossytnew** [mehmet-27/PunishManager#23]
**Describe the bug**
https://mcpaste.io/ec3c71cca2e272f0

software: pandaspigot
version: 1.8.9
java version: 1.18

**Expected behavior**
Well, I just put it in and set some configurations and I run it through a yaml validator and it tells me that everything is fine.

**Comment by mehmet-27** [comment]
Can you send your config file to me in discord server.
https://discord.gg/MYjmmEqKvE

**Comment by mehmet-27** [comment]
time out
